### PR TITLE
Updated respec for the publication

### PR DESCRIPTION
**Pull request by iherman**
The document should be assigned to the WG: changed the respec setup (plus some more minor things)

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-imp-guide/pull/11.html" title="Last updated on Aug 6, 2021, 9:57 AM UTC (034322f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-imp-guide/11/48c5452...034322f.html" title="Last updated on Aug 6, 2021, 9:57 AM UTC (034322f)">Diff</a>

### CODE REVIEW

**Comment by iherman** [comment]
@Orie, you can use the preview URL: ie, https://pr-preview.s3.amazonaws.com/w3c/did-imp-guide/pull/11.html for the pubrules checker while the PR is still open. Otherwise, if you want to use the pubrules' checker on the main branch, you can also use "https://labs.w3.org/spec-generator/?type=respec&url=https://w3c.github.io/did-imp-guide/"

Better merge it first and use the editor's draft imho.

(The spec-generator service runs respec in a headless browser, generating the pure HTML version of the document. Pubrules' checker does not have respec 'built in'.)

**Review by OR13 — APPROVED** [review]

**Comment by OR13** [comment]
@iherman I cannot merge this PR, I am not authorized.

**Comment by OR13** [comment]
@msporny ^^

**Comment by iherman** [comment]
> @iherman I cannot merge this PR, I am not authorized.

You are now... (I hope it worked, that is:-)

**Comment by OR13** [comment]
Screen Shot 2021-08-09 at 12 22 33 PM

**Comment by OR13** [comment]
@iherman I still cannot merge PRs ; (

**Comment by mprorock** [comment]
> @iherman I still cannot merge PRs ; (

same issue on my side - blocked as "not authorized"

**Comment by iherman** [comment]
I thought I did it, but it should be o.k. now (I probably forgot to do an explicit 'save'). @OR13, are you all set? B.t.w., @mprorock, you should also be set.

**Comment by mprorock** [comment]
Looks like it is resolved now, thanks!

**Pull request merged**
